# Generated by Django 2.2.10 on 2020-02-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0006_auto_20190710_2310'),
        ('visualize', '0004_auto_20170311_1514'),
    ]

    operations = [
    ]
