# Generated by Django 4.2 on 2024-04-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0012_alter_bookmark_content_type_and_more'),
        ('visualize', '0012_userlayer_password_protected'),
    ]

    operations = [
    ]
