from os.path import abspath, dirname, join
# from social.backends.google import GooglePlusAuth

# Absolute filesystem path to the Django project directory:
VISUALIZE_ROOT = dirname(dirname(dirname(abspath(__file__))))

# BASE_DIR = os.path.dirname(os.path.dirname(__file__))

SHOW_WATERMARK = False
DISCLAIMER_BUTTON_DEFAULT = False
USER_GEN_PREFIX = "User-Generated:"
USER_GEN_NOTICE = "Some content currently displayed was generated by users, not the Portal. Please review layer information in the 'Active' tab if you are unsure which information was user-generated."

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.DefaultStorageFinder',
    'compressor.finders.CompressorFinder',
    'npm.finders.NpmFinder'
)

NPM_ROOT_PATH = join(VISUALIZE_ROOT, 'mp-visualize', 'visualize')
# NPM_EXECUTABLE_PATH
# NPM_STATIC_FILES_PREFIX
# NPM_FILE_PATTERNS